name: Deploy to LangGraph Cloud

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Test graph creation
      run: |
        python -c "
        import sys
        sys.path.append('.')
        from rag_extraction.graph import create_extraction_graph
        graph = create_extraction_graph()
        print('✅ Graph creation successful')
        print('✅ Graph nodes:', list(graph.get_graph().nodes()))
        "
    
    - name: Validate schema
      run: |
        python -c "
        import sys
        sys.path.append('.')
        from rag_extraction.schemas.state import ExtractionState
        from rag_extraction.schemas.entities import ExtractedEntity
        
        # Test state creation
        state = ExtractionState(chunk_id='test')
        print('✅ ExtractionState validation successful')
        
        # Test entity creation
        entity = ExtractedEntity(name='test', entity_type='concept')
        print('✅ ExtractedEntity validation successful')
        "
    
    - name: Test node imports
      run: |
        python -c "
        import sys
        sys.path.append('.')
        from rag_extraction.nodes import retrieve_chunk, extract_entities, enhance_relationships, store_results
        print('✅ Node imports successful')
        "

  deploy-ready:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Deployment Ready Notification
      run: |
        echo "🚀 RAG Extraction LangGraph Application is ready for cloud deployment!"
        echo ""
        echo "📋 Deployment Details:"
        echo "   Repository: ${{ github.repository }}"
        echo "   Branch: ${{ github.ref_name }}"
        echo "   Commit: ${{ github.sha }}"
        echo ""
        echo "🔧 Next Steps:"
        echo "1. Go to https://smith.langchain.com"
        echo "2. Navigate to LangGraph Platform → '+ New Deployment'"
        echo "3. Select repository: ${{ github.repository }}"
        echo "4. Configure environment variables:"
        echo "   - OPENAI_API_KEY"
        echo "   - NEO4J_URI, NEO4J_USER, NEO4J_PASSWORD"
        echo "   - LANGCHAIN_API_KEY, LANGCHAIN_PROJECT"
        echo "5. Deploy to cloud (takes ~15 minutes)"
        echo ""
        echo "📊 Application Features:"
        echo "   - Semantic entity extraction with quality controls"
        echo "   - Multi-extractor workflow (concepts, methods, formulas, examples)"
        echo "   - Entity relationship discovery"
        echo "   - Comprehensive validation and error handling"
        echo "   - Production-ready cloud architecture"